apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-demo-orc
  labels:
    app: opa-demo-orc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-demo-orc
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 12345
        runAsGroup: 12345
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - all
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
        - name: opa
          image: openpolicyagent/opa:0.23.0-rootless
          ports:
            - containerPort: 8181