fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
    args:
    - '--allow-multiple-documents'
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-byte-order-marker
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.2.1
  hooks:
  - id: opa-check
  - id: opa-fmt
  - id: opa-test
    args: ['policy-example/', 'microservice-authz/policy/']
  - id: conftest-test
    args: ['--policy', 'conftest/policy']
    files: conftest/.*\.yaml$

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://gitlab.com/PyCQA/flake8
  rev: "3.8.3"
  hooks:
  - id: flake8
