apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-demo
  labels:
    app: mutating-webhook-demo
webhooks:
  - name: mutating-webhook-demo.default.svc.cluster.local
    clientConfig:
      caBundle: "" #${CA_BUNDLE}
      service:
        name: opa-webhook
        namespace: default
        path: "/v0/data/kubernetes/admission/mutating"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["*"]
    #namespaceSelector:
    #  matchLabels:
    #    mutateme: enabled


# https://github.com/alex-leonhardt/k8s-mutate-webhook